### ISSUE TITLE
SSL Connection to Presto

### ISSUE THREAD

**Issue by Vardhan17** [prestodb/presto-python-client#49]
I want to connect to an SSL enabled port using username & password, but I am not able to find any example of it on the web. The Presto is hosted on EMR cluster. 

Is there a possibility to use password at all?

**Comment by hustwolf** [comment]
i have the same problem
is there any answer?

**Comment by highker** [comment]
Do we know if we support SSL? @electrum

**Comment by hustwolf** [comment]
i use **pyhive** as the python client to presto
it supports ssl

**Comment by ggreg** [comment]
Looks like the problem here to use plain HTTP username/password authentication and to passe this information to the client.

**Comment by ggreg** [comment]
Basic auth is mentioned in #44.

**Comment by prakashin77** [comment]
> i use **pyhive** as the python client to presto
> it supports ssl

Hi 
I even tried with PyHive. Still facing issues

**Comment by Hyurt** [comment]
@ggreg Indeed Basic auth is needed. We used RPresto for querying with R. I provided and example here https://github.com/prestodb/RPresto/issues/107
However we need to ensure that the user passed into the basic auth is the same that the one used when querying. Otherwise you could by-pass access control rules and query catalogs or schemas that you shouldn't be allowed to query.

**Comment by ggreg** [comment]
Superseded by #44
