### ISSUE TITLE
DbApi is not PEP 249 compliant

### ISSUE THREAD

**Issue by davidecerri** [prestodb/presto-python-client#96]
https://www.python.org/dev/peps/pep-0249/#description

description should be allowed after execute. https://github.com/prestodb/presto-python-client/blob/master/prestodb/dbapi.py#L195
In the code, the description will not work unless a fetch is called.

Dropbox did this https://github.com/dropbox/PyHive/blob/master/pyhive/presto.py#L224 to support description after execute as required by PEP249

**Comment by oost** [comment]
I am having a similar issue when using in Airflow. 
The operator calls execute on the cursor and the description is empty (as _query.columns is empty), which prevents the DbApi hook from returning any records ([see here](https://github.com/apache/airflow/blob/45548b9451fba4e48c6f0c0ba6050482c2ea2956/airflow/providers/common/sql/hooks/sql.py#L68))
Did you close it because this was fixed? 
Thanks !
